clean-up

diff --git a/.github/workflows/3-env-cicd.yml b/.github/workflows/3-env-cicd.yml
--- a/.github/workflows/3-env-cicd.yml
+++ b/.github/workflows/3-env-cicd.yml
@@ -49,4 +49,6 @@ jobs:
       url: "http://www.demoApp.com"
     steps:
       - name: Deploy
-        run: echo I am deploying to prod env
+        run: |
+          echo I am deploying to production env
+          ## exit 1  ## uncomment if wanted to fail
